name: N Beats CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity 20 --max-line-length 127 --statistics
    - name: Build with Keras
      run: |
        make install-keras
    - name: Build with Pytorch
      run: |
        make install-pytorch
    - name: Run tests
      run: |
        make test

